[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.x" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.1" }
selene = { source = "kampfkarren/selene", version = "0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.17.1" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.2.1" }
