[package]
name = "vocksel/matter-replication"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [ "*" ]
include = [ "src", "src/**", "default.project.json", "README.md", "LICENSE", ]

[dependencies]
Matter = "matter-ecs/matter@0.7.1"
Freeze = "duckarmor/freeze@0.1.4"
